#!/usr/bin/env python3
"""
strategy_inventory.py

Fetches GET /qa/strategy_inventory (see docs/strategy_inventory_contract.md),
cross-checks reconciliation invariants, and writes a JSON + Markdown report.

This tool assumes the `qa` Cargo feature has been implemented per
docs/windows_test_control_contract.md. It does NOT parse Rust source directly —
source-parsing is an explicit fallback of last resort per the original directive
("never freeze a stale hardcoded list as the source of truth"), implemented only
if --source-fallback is passed and the live endpoint is unavailable.

Usage:
    python strategy_inventory.py --base-url http://127.0.0.1:11337 --api-key <key> \
        --out testlab_results/strategy_inventory

    python strategy_inventory.py --source-fallback --repo-path ../FreeDPI-Windows-master \
        --out testlab_results/strategy_inventory_static
"""
import argparse
import json
import re
import sys
import urllib.request
import urllib.error
from datetime import datetime, timezone
from pathlib import Path


def fetch_live_inventory(base_url: str, api_key: str) -> dict:
    req = urllib.request.Request(
        f"{base_url}/qa/strategy_inventory",
        headers={"X-API-Key": api_key},
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            envelope = json.loads(resp.read().decode("utf-8"))
    except urllib.error.URLError as e:
        print(f"FATAL: could not reach {base_url}/qa/strategy_inventory: {e}", file=sys.stderr)
        print("Is the app running with the 'qa' feature built and the API key correct?",
              file=sys.stderr)
        sys.exit(2)

    if not envelope.get("ok"):
        print(f"FATAL: /qa/strategy_inventory returned ok=false: {envelope.get('error')}",
              file=sys.stderr)
        sys.exit(2)
    return envelope["data"]


def source_fallback_inventory(repo_path: str) -> dict:
    """
    Last-resort static extraction. Only used when the live QA endpoint doesn't exist
    yet. Extracts:
      - StrategyProfileConfig-like blocks is NOT attempted here (TOML structure varies
        per config.toml actually shipped — parse config.toml, not Rust source, for
        live profiles).
      - numeric strategy_id literals referenced in probe/strategy_map.rs, as a rough
        cross-check only. This is intentionally coarse; it exists to unblock work
        before the /qa/ endpoint lands, not to replace it.
    """
    repo = Path(repo_path)
    strategy_map = repo / "src/core/src/probe/strategy_map.rs"
    numeric_ids = set()
    if strategy_map.exists():
        text = strategy_map.read_text(encoding="utf-8", errors="replace")
        numeric_ids = {int(m) for m in re.findall(r"strategy_id:\s*(\d+)", text)}
    else:
        print(f"WARNING: {strategy_map} not found under {repo_path}", file=sys.stderr)

    config_example = repo / "config.toml.example"
    live_profiles = []
    if config_example.exists():
        # Very coarse TOML-array-of-tables scan; a real TOML parser should replace
        # this once the agent confirms config.toml.example's actual [[strategies]]-
        # equivalent table name from config.rs's serde derive.
        text = config_example.read_text(encoding="utf-8", errors="replace")
        names = re.findall(r'name\s*=\s*"([^"]+)"', text)
        live_profiles = [{"name": n, "source_file": "config.toml.example"} for n in names]

    return {
        "live_profiles": live_profiles,
        "numeric_strategy_ids": sorted(numeric_ids),
        "dead_registry_entries": [
            {"note": "static fallback cannot determine reachability; run live QA endpoint for this field"}
        ],
        "reconciliation": {
            "mode": "source_fallback",
            "numeric_ids_total": len(numeric_ids),
            "live_profiles_total": len(live_profiles),
        },
        "_fallback_warning": (
            "This report was generated by static regex scanning, not the live app. "
            "Treat as approximate. Re-run with --base-url once /qa/strategy_inventory exists."
        ),
    }


def check_invariants(data: dict) -> list:
    """Returns a list of finding dicts: {severity, message}."""
    findings = []
    names = [p.get("name") for p in data.get("live_profiles", [])]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        findings.append({
            "severity": "fail",
            "message": f"Duplicate profile names in live_profiles: {sorted(dupes)}",
        })

    recon = data.get("reconciliation", {})
    unresolved = recon.get("numeric_ids_unresolved")
    if unresolved:
        findings.append({
            "severity": "warn",
            "message": (
                f"{unresolved} numeric strategy_id(s) referenced by "
                "probe::strategy_map::recommend() do not resolve to any live profile. "
                "AutoTune can recommend a strategy the engine cannot apply."
            ),
        })

    unreachable = recon.get("live_profiles_unreachable_by_any_numeric_id", [])
    if unreachable:
        findings.append({
            "severity": "info",
            "message": (
                f"{len(unreachable)} live profile(s) unreachable by AutoTune's automatic "
                f"path (expected for routing-only profiles): {unreachable}"
            ),
        })

    dead = data.get("dead_registry_entries", [])
    if dead:
        findings.append({
            "severity": "info",
            "message": (
                f"{len(dead)} StrategyRegistry entries confirmed unreachable from the "
                "traffic path (dead code) — see architecture_mapping.md."
            ),
        })

    return findings


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base-url", default="http://127.0.0.1:11337")
    ap.add_argument("--api-key", default="")
    ap.add_argument("--source-fallback", action="store_true")
    ap.add_argument("--repo-path", default="../FreeDPI-Windows-master")
    ap.add_argument("--out", default="strategy_inventory_report")
    args = ap.parse_args()

    if args.source_fallback:
        data = source_fallback_inventory(args.repo_path)
    else:
        data = fetch_live_inventory(args.base_url, args.api_key)

    findings = check_invariants(data)
    report = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "mode": "source_fallback" if args.source_fallback else "live_api",
        "data": data,
        "findings": findings,
    }

    out_json = Path(f"{args.out}.json")
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(report, indent=2), encoding="utf-8")

    lines = [f"# Strategy inventory report ({report['mode']})", ""]
    lines.append(f"Generated: {report['generated_at_utc']}")
    lines.append("")
    lines.append("## Findings")
    if not findings:
        lines.append("- none")
    for f in findings:
        lines.append(f"- **{f['severity'].upper()}**: {f['message']}")
    out_md = Path(f"{args.out}.md")
    out_md.write_text("\n".join(lines), encoding="utf-8")

    fails = [f for f in findings if f["severity"] == "fail"]
    print(f"Wrote {out_json} and {out_md}")
    print(f"{len(fails)} fail-severity finding(s)")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
